import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "react-hot-toast";

import {
  Navbar
} from "@/global/components";

import {
  Logo
} from "@/features/dashboard";


import "./globals.css";
import { Monda } from "next/font/google";

const monda = Monda({
  subsets: ["latin"],
  weights: [100, 200, 300, 400, 500, 600, 700],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${monda.className}`}>
        <Toaster />
        <Logo />
        {children}
        <Navbar />
      </body>
    </html>
  );
}
