<<<<<<< HEAD
import {
  Logo
} from "@/features/dashboard";
=======
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "react-hot-toast";
>>>>>>> origin/development

import {
  Navbar
} from "@/global/components";

import "./globals.css";
import { Monda } from "next/font/google";

const monda = Monda({
  subsets: ["latin"],
  weights: [100, 200, 300, 400, 500, 600, 700],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={monda.className}>
        <Logo />
=======
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />
>>>>>>> origin/development
        {children}
        <Navbar />
      </body>
    </html>
  );
}
